### ISSUE TITLE
Tag component options

### ISSUE THREAD

**Issue by GabrielSt** [Douro-ui/design-system#119] opened 2024-09-25 14:16 UTC
**Describe the bug**
The tag component could assume the type by checking if the src is provided, if it is, it's an image type. If there's a logic that makes it harder, make the type required, in my case, I've placed the src and it didn't work, because the type was not settled.

Remove the cursor pointer on that, it will not always be clickable, so the client should apply those rules upon need.

**To Reproduce**

Implement packages/components/avatar/src/Avatar.tsx

**Comment by Arthurmqz** [comment] 2024-09-26 11:48
The PR for this issue https://github.com/Douro-ui/design-system/pull/121

**Comment by Arthurmqz** [comment] 2024-10-07 09:08
The issue is fixed in this commit https://github.com/Douro-ui/design-system/commit/8173dd489e43d7917007ce1ad1d838e2e58cfc5a

**Closed** 2024-10-07 09:08 UTC
Labels: enhancement
